### ISSUE TITLE
Building failure with MEMKIND

### ISSUE THREAD

**Issue by adam-abed-abud** [pmem/redis#181]
Hi! 
I would like to use REDIS on a centos 7 machine with only PMEM  but unfortunately I cannot build the software.
Here are the commands that I run:

yum -y install memkind-devel
git clone https://github.com/pmem/redis.git && cd redis/
make MALLOC=memkind

Here are the errors:
error: ‘MEMKIND_DAX_KMEM’ undeclared
error: ‘MEMKIND_STAT_TYPE_RESIDENT’ undeclared
error: ‘MEMKIND_STAT_TYPE_ACTIVE’ undeclared
error: ‘MEMKIND_STAT_TYPE_ALLOCATED’ undeclared 

I also tried with the following make command and I got the same errors:
make USE_PMDK=yes STD=-std=gnu99 MALLOC=memkind

Any suggestions?

Thanks a lot

**Comment by michalbiesek** [comment]
Hi,
I believe centos7 don't have yet newest memkind version in their package repositories. That's why you see errors during build.

What I could suggest to you is to build and install yourself a version from official release:
https://github.com/memkind/memkind/releases, you could use one of following versions:

- https://github.com/memkind/memkind/releases/tag/v1.10.0
- https://github.com/memkind/memkind/releases/tag/v1.10.1-rc1

The build instruction is presented here:
https://github.com/memkind/memkind/tree/master#building-and-installing

Quick pro tip, regarding usage of MEMKIND_DAX_KMEM:
**Before** building and installing libmemkind from sources please ensure that, you have libdaxctl-devel (v66 or later) installed on your machine.
Other requirements, like kernel and system configuration related to this kind are described in:
https://pmem.io/2020/01/20/memkind-dax-kmem.html

Best Regards Michal

**Comment by adam-abed-abud** [comment]
Fantastic! This is very useful, thank you so much.

I compiled memkind from source without MEMKIND_DAX_KMEM. After that I built pmem/redis and it worked fine. However, when I start the redis server it rightfully complains because of "undefined symbol: MEMKIND_DAX_KMEM"

Do you know if it is possible to disable MEMKIND_DAX_KMEM ? I see that one of the system requirements is to have kernel version 5.1 but on the machine I'm using it is set to 4.15 and I cannot upgrade it.

**Comment by michalbiesek** [comment]
Hi,
I suspect you have installed 2 memkind libraries - please call `ldd redis-server` command in src directory and see where leads path to **libmemkind** - I believe it would lead to .so file from yum repository which doesn't have MEMKIND_DAX_KMEM. To avoid this issue in future I recommend to remove the libmemkind installed from yum and use only the one you build and installed. You could also try to set LD_LIBRARY_PATH.

Regarding usage of MEMKIND_DAX_KMEM:
- from libmemkind perspective you could emulate the PMEM node described in https://pmem.io/2020/01/20/memkind-dax-kmem.html using MEMKIND_DAX_KMEM_NODES.
- from redis perspective see that if you use only-dram configuration (this is used currently by default) https://github.com/pmem/redis/blob/9a3af0f52252f82f099cefb95520ad1a2d90591c/redis.conf#L1782-L1788 - in this configuration you will not use MEMKIND_DAX_KMEM at all

Please be aware that this is working branch as we perform changes here and in libmemkind libraries to achievement best results.

**Comment by adam-abed-abud** [comment]
Hi,
Yes indeed there were two memkind libraries installed and I fixed it now. 

I'd prefer to go through the main route and I will try to upgrade my machine to the latest kernel version. 

Thanks a lot!
